scrape_configs:
  - job_name: "masool-collection"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 3s # how often to scrape
    static_configs:
      - targets: ["host.docker.internal:80"]